# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
# We basically "mock" any imports that are not absolutely necessary, and so don't
# need to install much (not even hera_sim!)
python:
  version: 3.6
  system_packages: true
  install:
    - requirements: requirements_dev.txt
    - requirements: docs/requirements.txt
