# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "3.2.1.dev109+g56c708f0.d20230802"
__version_tuple__ = version_tuple = (3, 2, 1, "dev109", "g56c708f0.d20230802")
