# Run template for latest fiducial grid-based 21cmfast runs

[CosmoParams]

[UserParams]
HII_FILTER = 1

[AstroParams]
R_BUBBLE_MAX = 50.0

[FlagOptions]
USE_HALO_FIELD = false
HALO_STOCHASTICITY = false
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_MINI_HALOS = false
USE_TS_FLUCT = true
INHOMO_RECO = true
