# Run template for latest fiducial grid-based 21cmfast runs

[CosmoParams]

[UserParams]

[AstroParams]

[FlagOptions]
USE_HALO_FIELD = false
HALO_STOCHASTICITY = false
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_MINI_HALOS = false
USE_TS_FLUCT = true
INHOMO_RECO = true
