# Run template for simple 21cmfast runs

[CosmoParams]

[UserParams]
HII_FILTER = 'sharp-k'

[AstroParams]

[FlagOptions]
USE_HALO_FIELD = false
HALO_STOCHASTICITY = false
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_MINI_HALOS = false
USE_TS_FLUCT = false
INHOMO_RECO = false
