# Run template for simple 21cmfast runs

[CosmoParams]

[SimulationOptions]
HII_DIM=48
BOX_LEN=64

[MatterOptions]
USE_HALO_FIELD = false
HALO_STOCHASTICITY = false

[AstroParams]

[AstroOptions]
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_UPPER_STELLAR_TURNOVER = false
USE_MINI_HALOS = false
USE_TS_FLUCT = false
INHOMO_RECO = false
HII_FILTER = 'sharp-k'
ZPRIME_STEP_FACTOR = 1.2
Z_HEAT_MAX = 20
