[CosmoParams]

[SimulationOptions]
HII_DIM=64
HIRES_TO_LOWRES_FACTOR=3
LOWRES_CELL_SIZE_MPC=1.5
ZPRIME_STEP_FACTOR = 1.1
Z_HEAT_MAX = 35

[MatterOptions]

[AstroParams]
R_BUBBLE_MAX = 32

[AstroOptions]
