name: Labeler

on: push

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
