name: Merge me!

on:
  pull_request:
    types:
      - edited
      - labeled
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-pr')
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v1
        with:
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_TOKEN: ${{ secrets.BUMP_VERSION }}
          GITHUB_LOGIN: steven-murray
          MERGE_METHOD: REBASE
